services:
  - type: web
    name: reserva-tu-cancha
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://www.reservatuscanchas.cl
      - key: DATABASE_URL
        fromDatabase:
          name: reserva-tu-cancha-db
          property: connectionString
      - key: SMTP_HOST
        value: smtp.zoho.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        value: soporte@reservatuscanchas.cl
      - key: SMTP_PASS
        value: KWAX CS8q 61cN
    healthCheckPath: /health
    autoDeploy: true
    # Forzar redeploy para código de reserva corto - Versión 4
    branch: main
    region: oregon

  - type: pserv
    name: reserva-tu-cancha-db
    env: postgresql
    plan: free
    region: oregon
